package ca.carsXML;

import java.io.File;
import java.io.IOException;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Result;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.stream.StreamSource;

import org.w3c.dom.Document;
import org.xml.sax.SAXException;

/**
 * Copyright (c) 2006 Sun Microsystems, Inc.  All rights reserved.
 * 
 * Process an XML document using an XSLT stylesheet in Java - to genertate 
 * stylized html file or show in console
 */
public class XmlStylizer {

	// Global value so it can be ref'd by the tree-adapter
    static Document document;

    public static void main(String[] argv) {

    	if (argv.length != 3) {
            System.err.println("Usage: java XmlStylizer stylesheet xmlfile htmlfile");
            System.err.println("Usage: java XmlStylizer students.xsl students.xml students.html");
            System.exit(1);
        }

        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        
        //the DocumentBuilderFactory defines a factory API that enables applications to configure 
        //and obtain a parser to parse XML documents into a DOM Document tree

        //factory.setNamespaceAware(true);
        //factory.setValidating(true);
        try {
            File stylesheet = new File(argv[0]);
            File datafile = new File(argv[1]);
            File htmlfile = new File(argv[2]);

            DocumentBuilder builder = factory.newDocumentBuilder();
            // DocumentBuilder: Defines the API to obtain DOM Document instances from an XML document
            document = builder.parse(datafile);

            //1. Obtain a TransformerFactory object.
            TransformerFactory tFactory = TransformerFactory.newInstance();
            //A TransformerFactory instance can be used to create Transformer and Templates objects.
            
            //2. Present the stylesheet as a Source
            StreamSource stylesource = new StreamSource(stylesheet);
            //StreamSource: Acts as an holder for a transformation Source in the form of a stream of XML markup.
            
            //3. Use the factory object to obtain a Transformer object for the given stylesheet
            Transformer transformer = tFactory.newTransformer(stylesource);
            //Transformer:An instance of this abstract class can transform a source tree into a result tree.

            //4. Present the input document as a Source
            DOMSource source = new DOMSource(document);
            
            //DOMSource:Acts as a holder for a transformation 
            //Source tree in the form of a Document Object Model (DOM) tree.
            
            //5. Provide a Result object to accept the output document
            StreamResult result = new StreamResult(System.out); // to console
            Result outputResult = new StreamResult(htmlfile); // to htmlfile
            
            //6. Use the Transformer object to transform the input document
            transformer.transform(source, result);   // to console
            transformer.transform(source, outputResult); // to htmlfile
            
        } catch (TransformerConfigurationException tce) {
            // Error generated by the parser
            System.out.println("\n** Transformer Factory error");
            System.out.println("   " + tce.getMessage());

            // Use the contained exception, if any
            Throwable x = tce;

            if (tce.getException() != null) {
                x = tce.getException();
            }

            x.printStackTrace();
        } catch (TransformerException te) {
            // Error generated by the parser
            System.out.println("\n** Transformation error");
            System.out.println("   " + te.getMessage());

            // Use the contained exception, if any
            Throwable x = te;

            if (te.getException() != null) {
                x = te.getException();
            }

            x.printStackTrace();
        } catch (SAXException sxe) {
            // Error generated by this application
            // (or a parser-initialization error)
            Exception x = sxe;

            if (sxe.getException() != null) {
                x = sxe.getException();
            }

            x.printStackTrace();
        } catch (ParserConfigurationException pce) {
            // Parser with specified options can't be built
            pce.printStackTrace();
        } catch (IOException ioe) {
            // I/O error
            ioe.printStackTrace();
        }
    } // main
}